version: '3.8'

services:
  api:
    build: .
    container_name: fx-forecast-api
    ports:
      - "8767:8767"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./alembic:/app/alembic
      - ../docs:/app/docs
    environment:
      - DATABASE_URL=sqlite:////app/data/fx_forecast.db
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8767 --reload