"""Add unique constraints to prevent duplicate data

Revision ID: 087c3debb963
Revises: consolidated_001
Create Date: 2025-06-30 12:23:35.153907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087c3debb963'
down_revision: Union[str, None] = 'consolidated_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add unique constraint to forex_rates to prevent duplicate data for same timestamp
    op.create_unique_constraint(
        'uq_forex_rates_pair_timestamp', 
        'forex_rates', 
        ['currency_pair', 'timestamp']
    )
    
    # Add unique constraint to technical_indicators to prevent duplicate data for same timestamp and timeframe
    op.create_unique_constraint(
        'uq_technical_indicators_symbol_timeframe_timestamp',
        'technical_indicators',
        ['symbol', 'timeframe', 'timestamp']
    )
    
    # Keep the original changes
    op.drop_index('idx_entry_signals_symbol_timeframe', table_name='entry_signals')
    op.create_index(op.f('ix_entry_signals_symbol'), 'entry_signals', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the unique constraints
    op.drop_constraint('uq_forex_rates_pair_timestamp', 'forex_rates', type_='unique')
    op.drop_constraint('uq_technical_indicators_symbol_timeframe_timestamp', 'technical_indicators', type_='unique')
    
    # Restore the original index
    op.drop_index(op.f('ix_entry_signals_symbol'), table_name='entry_signals')
    op.create_index('idx_entry_signals_symbol_timeframe', 'entry_signals', ['symbol', 'timeframe'], unique=False)
    # ### end Alembic commands ###