"""add candlestick and technical_indicators tables v2

Revision ID: 1426ac8f7c28
Revises: a53fd2c058a2
Create Date: 2025-06-30 05:24:58.477298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1426ac8f7c28'
down_revision: Union[str, None] = 'a53fd2c058a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candlestick_data',
    sa.Column('symbol', sa.TEXT(), nullable=False),
    sa.Column('timeframe', sa.TEXT(), nullable=False),
    sa.Column('open_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('close_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('open_price', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('high_price', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('low_price', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('close_price', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('tick_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timeframe', 'open_time')
    )
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ema_5', sa.Float(), nullable=True),
    sa.Column('ema_10', sa.Float(), nullable=True),
    sa.Column('ema_15', sa.Float(), nullable=True),
    sa.Column('ema_20', sa.Float(), nullable=True),
    sa.Column('ema_50', sa.Float(), nullable=True),
    sa.Column('ema_100', sa.Float(), nullable=True),
    sa.Column('ema_200', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_middle', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('stoch_k', sa.Float(), nullable=True),
    sa.Column('stoch_d', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_technical_indicators_symbol_timeframe_timestamp', 'technical_indicators', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_technical_indicators_id'), 'technical_indicators', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technical_indicators_id'), table_name='technical_indicators')
    op.drop_index('idx_technical_indicators_symbol_timeframe_timestamp', table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_table('candlestick_data')
    # ### end Alembic commands ###