"""initial tables

Revision ID: c3fcf00d1bf5
Revises: 
Create Date: 2025-06-24 00:58:54.427412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fcf00d1bf5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forex_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_rate', sa.Float(), nullable=False),
    sa.Column('confidence_interval', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forex_forecasts_currency_pair'), 'forex_forecasts', ['currency_pair'], unique=False)
    op.create_index(op.f('ix_forex_forecasts_id'), 'forex_forecasts', ['id'], unique=False)
    op.create_table('forex_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forex_rates_currency_pair'), 'forex_rates', ['currency_pair'], unique=False)
    op.create_index(op.f('ix_forex_rates_id'), 'forex_rates', ['id'], unique=False)
    op.create_index(op.f('ix_forex_rates_timestamp'), 'forex_rates', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_forex_rates_timestamp'), table_name='forex_rates')
    op.drop_index(op.f('ix_forex_rates_id'), table_name='forex_rates')
    op.drop_index(op.f('ix_forex_rates_currency_pair'), table_name='forex_rates')
    op.drop_table('forex_rates')
    op.drop_index(op.f('ix_forex_forecasts_id'), table_name='forex_forecasts')
    op.drop_index(op.f('ix_forex_forecasts_currency_pair'), table_name='forex_forecasts')
    op.drop_table('forex_forecasts')
    # ### end Alembic commands ###