"""TimescaleDB schema with composite keys

Revision ID: a2926eecdbe6
Revises: 
Create Date: 2025-06-29 16:00:16.041402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2926eecdbe6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_results',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.TEXT(), nullable=False),
    sa.Column('analysis_timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('timeframe', sa.TEXT(), nullable=False),
    sa.Column('entry_signal', sa.TEXT(), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('reasoning', sa.TEXT(), nullable=True),
    sa.Column('technical_data', sa.JSON(), nullable=True),
    sa.Column('anthropic_response', sa.JSON(), nullable=True),
    sa.Column('notification_sent', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candlestick_data',
    sa.Column('symbol', sa.TEXT(), nullable=False),
    sa.Column('timeframe', sa.TEXT(), nullable=False),
    sa.Column('open_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('close_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('open_price', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('high_price', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('low_price', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('close_price', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('tick_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timeframe', 'open_time')
    )
    op.create_table('forex_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(), nullable=False),
    sa.Column('forecast_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('predicted_rate', sa.Float(), nullable=False),
    sa.Column('confidence_interval', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forex_forecasts_currency_pair'), 'forex_forecasts', ['currency_pair'], unique=False)
    op.create_index(op.f('ix_forex_forecasts_id'), 'forex_forecasts', ['id'], unique=False)
    op.create_table('forex_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forex_rates_currency_pair'), 'forex_rates', ['currency_pair'], unique=False)
    op.create_index(op.f('ix_forex_rates_id'), 'forex_rates', ['id'], unique=False)
    op.create_index(op.f('ix_forex_rates_timestamp'), 'forex_rates', ['timestamp'], unique=False)
    op.create_table('price_zones',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.TEXT(), nullable=False),
    sa.Column('zone_type', sa.TEXT(), nullable=False),
    sa.Column('price_level', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('strength', sa.INTEGER(), nullable=True),
    sa.Column('first_touch', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_touch', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('touch_count', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_indicators',
    sa.Column('symbol', sa.TEXT(), nullable=False),
    sa.Column('timeframe', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('indicator_type', sa.TEXT(), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timeframe', 'timestamp', 'indicator_type')
    )
    op.create_table('tick_data',
    sa.Column('symbol', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('bid', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('ask', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('notification_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.BIGINT(), nullable=True),
    sa.Column('notification_type', sa.TEXT(), nullable=False),
    sa.Column('recipient', sa.TEXT(), nullable=False),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analysis_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # TimescaleDB hypertables creation
    op.execute("SELECT create_hypertable('tick_data', 'timestamp', chunk_time_interval => INTERVAL '1 hour')")
    op.execute("SELECT create_hypertable('candlestick_data', 'open_time', chunk_time_interval => INTERVAL '1 day')")
    op.execute("SELECT create_hypertable('technical_indicators', 'timestamp', chunk_time_interval => INTERVAL '1 day')")
    
    # Create optimized indexes for time-series queries
    op.create_index('idx_tick_symbol_time', 'tick_data', ['symbol', 'timestamp'])
    op.create_index('idx_candlestick_symbol_timeframe_time', 'candlestick_data', ['symbol', 'timeframe', 'open_time'])
    op.create_index('idx_indicators_lookup', 'technical_indicators', ['symbol', 'timeframe', 'indicator_type', 'timestamp'])
    op.create_index('idx_ai_analysis_symbol_time', 'ai_analysis_results', ['symbol', 'analysis_timestamp'])
    op.create_index('idx_ai_analysis_signals', 'ai_analysis_results', ['entry_signal', 'notification_sent'])
    op.create_index('idx_zones_symbol_active', 'price_zones', ['symbol', 'is_active'])
    op.create_index('idx_zones_price', 'price_zones', ['symbol', 'price_level'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop custom indexes first  
    op.drop_index('idx_zones_price', table_name='price_zones')
    op.drop_index('idx_zones_symbol_active', table_name='price_zones')
    op.drop_index('idx_ai_analysis_signals', table_name='ai_analysis_results')
    op.drop_index('idx_ai_analysis_symbol_time', table_name='ai_analysis_results')
    op.drop_index('idx_indicators_lookup', table_name='technical_indicators')
    op.drop_index('idx_candlestick_symbol_timeframe_time', table_name='candlestick_data')
    op.drop_index('idx_tick_symbol_time', table_name='tick_data')
    
    op.drop_table('notification_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tick_data')
    op.drop_table('technical_indicators')
    op.drop_table('price_zones')
    op.drop_index(op.f('ix_forex_rates_timestamp'), table_name='forex_rates')
    op.drop_index(op.f('ix_forex_rates_id'), table_name='forex_rates')
    op.drop_index(op.f('ix_forex_rates_currency_pair'), table_name='forex_rates')
    op.drop_table('forex_rates')
    op.drop_index(op.f('ix_forex_forecasts_id'), table_name='forex_forecasts')
    op.drop_index(op.f('ix_forex_forecasts_currency_pair'), table_name='forex_forecasts')
    op.drop_table('forex_forecasts')
    op.drop_table('candlestick_data')
    op.drop_table('ai_analysis_results')
    # ### end Alembic commands ###